# Generated by Django 3.2.9 on 2022-05-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAcc',
            fields=[
                ('AccID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.TextField()),
                ('Address', models.TextField()),
                ('phno', models.IntegerField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('DateCreated', models.DateField()),
                ('TimeCreated', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('TranID', models.AutoField(primary_key=True, serialize=False)),
                ('DrAmnt', models.IntegerField()),
                ('CrAmnt', models.IntegerField()),
                ('Desc', models.TextField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('AccNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customeracc')),
            ],
        ),
    ]
