# Generated by Django 3.2.9 on 2022-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customeracc_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='TranID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customeracc',
            name='AccID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
