# Generated by Django 3.2.9 on 2022-06-08 13:07

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220517_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='AccName',
            field=models.CharField(default=builtins.dir, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeracc',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customeracc',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customeracc',
            name='phno',
            field=models.IntegerField(null=True),
        ),
    ]
