# Generated by Django 3.2.9 on 2022-06-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220608_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeracc',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeracc',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customeracc',
            name='phno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
