# Generated by Django 3.2.9 on 2022-06-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220608_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='TranID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
