# Generated by Django 3.2.9 on 2022-06-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cashbook_tranid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeracc',
            name='AccID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
