# Generated by Django 4.0.5 on 2022-06-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customeracc_accid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='TranID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
