# Generated by Django 4.0.6 on 2022-10-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_cashbook_tranid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.TextField(null=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customeracc')),
            ],
        ),
    ]
