# Generated by Django 4.0.6 on 2022-11-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_lastbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeracc',
            name='Balance',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='LastBalance',
        ),
    ]
