# Generated by Django 4.0.6 on 2022-11-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customeracc_balance_delete_lastbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeracc',
            old_name='Balance',
            new_name='LastBalance',
        ),
    ]
