# Generated by Django 4.1.7 on 2023-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_rename_balance_customeracc_lastbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoCount",
            fields=[
                ("Nid", models.AutoField(primary_key=True, serialize=False)),
                ("Rdate", models.DateField()),
                ("R2000", models.IntegerField(blank=True, null=True)),
                ("R500", models.IntegerField(blank=True, null=True)),
                ("R200", models.IntegerField(blank=True, null=True)),
                ("R100", models.IntegerField(blank=True, null=True)),
                ("R50", models.IntegerField(blank=True, null=True)),
                ("RCh", models.IntegerField(blank=True, null=True)),
                ("Ronl", models.IntegerField(blank=True, null=True)),
                ("Total", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
