# Generated by Django 4.1.7 on 2023-05-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_nocount"),
    ]

    operations = [
        migrations.AddField(
            model_name="nocount",
            name="Remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
